version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: GD_CUST
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: GD_CUST
      MYSQL_USER: GD_CUST
      MYSQL_PASSWORD: GD_CUST
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: GD_CUST
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:
    driver: local
